name: Jekyll Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: |
          gem install bundler jekyll
          bundle install
          bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: _site
      - uses: actions/deploy-pages@v1
